// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import FlashController from "./flash_controller.js";
application.register("flash", FlashController);

import PageReloadController from "./page_reload_controller.ts";
application.register("page-reload", PageReloadController);

import PaypalClientController from "./paypal_client_controller.ts";
application.register("paypal-client", PaypalClientController);

import ToggleTransactionsController from "./toggle_transactions_controller.ts";
application.register("toggle-transactions", ToggleTransactionsController);
